#' Calculate the probability of motif occurrence in each sequence
#' @description This function calculates the probability of motif occurrence in each sequence and counts the number of non-overlapping motif occurrences.
#' The probability of motif occurrence is calculated using a Markov chain and becomes increasingly computationally exhaustive given the length and number of motifs.
#' Therefore, the function is parallelized to speed up computation and at least 16 cores with 128 GB of RAM is recommended when running the function for all 7-mers.
#'
#' @param motifs a vector of motifs (e.g., c("ACGTAGT", "GTACAAG")) or an integer specifying the k-mers to be used (e.g., 7 for all 7-mers). A motif is specified as a regular expression on the alphabet {A,C,G,T}.
#' @param seqs a dataframe with the columns: 'gid', 'sequence', and 'nchar' (generated by build_seq_list()).
#' @param seqlist a list of sequences (generated by build_seq_list()).
#' @param paths boolean specifying whether the input data is provided as file paths or as R objects.
#' @param binom_approx boolean specifying whether to use a binomial approximation to calculate motif probabilities or the default n-step TPM assuming an underlying Markov chain. The binomial method assumes a random and independent distribution of nucleotides in the sequence of interest. The approach is most appropriate when considering a large set of longer k-mers (> 7-mers). If binom_approx = T, 'motifs' has to be specified as a k-mer (e.g., motifs = 8 for all 8-mers).
#' @param cores number of cores to use for parallelization. Consider increasing number of cores for long k-mers (default is the number of cores available).
#' @param out_path path to output directory (default is NULL, where the output is returned rather than saved).
#' @param include_counts the default is TRUE and ensures that the matrix with motif counts is also returned. This parameter should ONLY be FALSE when running a light-weight approx. approach on a smaller computer.
#' @param markov_order integer specifying order of motif background model: 0 uses nucleotide frequencies (default), and 1 uses dinucleotide transition probabilities.
#'
#' @return two matrices, motif_probs and motif_counts, containing sequence-specific motif probabilities and motif counts, respectively.
#' @export
#'
#' @examples
#' \dontrun{
#' motif_prob_count_lst <- motif_prob(motifs = c("ACGTAGT", "GTACAAG"),
#' seqs = "./seqs.rds", seqlist = "./seqlist.rds",
#' binom_approx = F, cores = 4)
#'
#' motif_prob(motifs = 7, seqs = seqs, seqlist = seqlist, paths = F,
#' binom_approx = T, out_path = "./")
#' }
#'
#'
#'
motif_prob <- function(motifs, seqs, seqlist, paths = T, binom_approx = F, cores = parallel::detectCores(),
                       out_path = NULL, include_counts = T, markov_order = 0) {

  # load data if file paths are provided
  if(paths) {
    seqs <- readRDS(seqs)
    seqlist <- readRDS(seqlist)
  }
  # check if integer is specified to obtain all k-mers
  motifs_int <- motifs
  if (is.numeric(motifs) && length(motifs) == 1 && motifs == floor(motifs)) {
    motifs_int <- as.integer(motifs_int)
    motifs <- Regmex::all.mers(motifs_int)
  }

  ## Extract non-overlapping motif counts for each sequence ##
  if (include_counts) { # consider adding grep for binom_approx == T (Faster approach to getting count data)
    motif_counts <- do.call(cbind, parallel::mclapply(motifs, function(x) Regmex::n.obs.mot(x, seqlist, overlap =F), mc.cores = cores))
    colnames(motif_counts) <- motifs
    rownames(motif_counts) <- seqs$gid # match sequence and expression names/gene IDs
  }

  ## Calculate motif probabilities for each sequence ##
  if (binom_approx == F) {
    # generate state-space matrix (used to construct Markov chain; consisting of initial state and transition probabilities)
    pat.con <- utils::getFromNamespace("pat.con", "Regmex")
    patterns <- parallel::mclapply(motifs, function(x) pat.con(x, overlap = F), mc.cores = cores)
    names(patterns) <- motifs

    # compute probability of motif occurrence in each sequence
    motif_probs <- do.call(cbind, parallel::mclapply(patterns, function(x) unlist(lapply(seqlist, function(y) bayesReact::pd_mrs2(x,y, markov_order = markov_order))), mc.cores = cores))
    colnames(motif_probs) <- motifs
    rownames(motif_probs) <- seqs$gid # match sequence and expression names/gene IDs

    # check for NAs
    #if (anyNA(motif_probs)) {stop("NA/NaN introduced when calculating motif probabilities. Try checking input data for errors.", call. = FALSE)}

  } else { # Binomial approximation (consider MMN implementation, which includes faster motif counts)

    # check that the method is only used for k-mers
    if(!is.numeric(motifs_int)) stop("'motifs' should be an integer specifying k-mers to by used. Alternatively, consider using binom_approx = F.", call. = F)

    # pre-compute motif and seq representations to avoid repeated reconstruction for each mot and seq pair
    nt_idx <- c(A = 1L, C = 2L, G = 3L, T = 4L) # integer indexing (possible due to consistent ordering)
    nts <- c("A", "C", "G", "T")
    motif_idx <- lapply(motifs, function(m) nt_idx[strsplit(m, "", fixed = TRUE)[[1L]]]) # convert each motif to integer indices once
    k <- motifs_int
    S <- length(seqlist) # number of sequences
    M <- length(motifs) # number of motifs
    seq_lens <- vapply(seqlist, function(y) y$length, integer(1L))

    # store nt freqs as S x 4 matrix once
    seqs_freq_nt <- do.call(rbind, lapply(seqlist, function(y) y$freq.mono[nts]))
    seqs_freq_nt[is.na(seqs_freq_nt)] <- 0
    seqs_freq_nt_log <- log(seqs_freq_nt) # work in log-space for numerical stability

    # store conditional probs (di-nt) once (only if 1st-order model): stack con.prob.di as 4 (m_i) x 4 (m_{i-1}) x S array
    # Important: in con.prob.di cols sum to 1, so con.prob.di[i, j] = P(m_i = i | m_{i-1} = j), for m = m_1...m_k
    if (markov_order == 1L) {
      cond_prob_log <- array(unlist(lapply(seqlist, function(y) log(as.numeric(y$con.prob.di[nts, nts])))), dim = c(4L, 4L, S))
      cond_prob_log[!is.finite(cond_prob_log)] <- -Inf
    }

    # calculate probability of at least one motif occurrence in each sequence (done motif-wise across all seqs)
    binom_ssp <- if (markov_order == 0L) { # 0th-order: SSP from nt freqs
      function(m){
        mot <- motif_idx[[m]]
        SSP_m <- numeric(S)
        seqs_eval <- seq_lens >= k # handle motif longer than seq (SSP = 0)
        # probability of each nt in the motif is its frequency in the sequence
        mot_occ_prob_log <- rowSums(seqs_freq_nt_log[seqs_eval, mot, drop = FALSE]) # probability of motif occurrence (success at each trial) is the sum of the log-probs of each nt in the motif
        trials <- seq_lens[seqs_eval] - k + 1 # number of trials is the number of positions where a motif can potentially occur in the sequence

        # probability of at least one motif occurrence in the sequence thus becomes '1 - probability of no motif occurrence'
        # SSP = 1 - (1 - P(m))^trials (log1p & expm1 to handle small P(m))
        SSP_m[seqs_eval] <- -expm1(trials * log1p(-exp(pmin(mot_occ_prob_log, 0))))
        return(SSP_m)
      }
    } else if (markov_order == 1L) { # 1st-order: SSP from dinucleotide context via conditional probs
      function(m){
        mot <- motif_idx[[m]]
        SSP_m <- numeric(S)
        seqs_eval <- seq_lens >= k
        n_seqs_eval <- sum(seqs_eval) # number of seqs passing the length filter
        mot_occ_prob_pos1_log <- seqs_freq_nt_log[seqs_eval, mot[1L]] # marginal prob. at first nt position
        if (k == 1L) {
          mot_occ_prob_log <- mot_occ_prob_pos1_log
        } else {
          # Conditional prob: P(m_i | m_i-1) = P(m_i, m_i-1) / P(m_i-1)
          m_cond_prob_log <- matrix( # Account for di-nt context through conditional probabilities
            vapply(seq_len(k - 1L), function(i) cond_prob_log[mot[i + 1L], mot[i], seqs_eval], numeric(n_seqs_eval)),
            nrow = n_seqs_eval)
          mot_occ_prob_log <- mot_occ_prob_pos1_log + rowSums(m_cond_prob_log)
        }
        trials <- seq_lens[seqs_eval] - k + 1

        # probability of at least one motif occurrence in the sequence thus becomes '1 - probability of no motif occurrence'
        SSP_m[seqs_eval] <- -expm1(trials * log1p(-exp(pmin(mot_occ_prob_log, 0))))
        return(SSP_m)
      }
    } else {
      stop("'markov_order' should be either 0 or 1.", call. = F)
    }
    # pre-allocate SSP matrix (fill in chunks to bound max memory)
    motif_probs <- matrix(0, nrow = S, ncol = M, dimnames = list(seqs$gid, motifs))
    chunk_size <- min(256, 4^k)

    # iterate over motif chunks
    for (start in seq.int(1L, M, by = chunk_size)) {
      idx <- start:min(start + chunk_size - 1, M)
      SSP_chunk <- parallel::mclapply(idx, binom_ssp, mc.cores = cores)
      for (mots in seq_along(idx)) motif_probs[, idx[mots]] <- SSP_chunk[[mots]]
      rm(SSP_chunk)
    }
  }

  ## Save or return motif probabilities ##
  if (include_counts == F){
    if (is.character(out_path)) {
      if(substring(out_path, nchar(out_path)) != "/"){out_path <- paste0(out_path, "/")}
      saveRDS(motif_probs, file = paste0(out_path, "seqXmot_probs.rds"))
      return(list(motif_probs_path = paste0(out_path, "seqXmot_probs.rds"))) # used by process_raw_input()
    } else {
      return(motif_probs)
    }
  }

  if (is.character(out_path)) {
    if(substring(out_path, nchar(out_path)) != "/"){out_path <- paste0(out_path, "/")}
    saveRDS(motif_counts, file = paste0(out_path, "seqXmot_counts.rds"))
    saveRDS(motif_probs, file = paste0(out_path, "seqXmot_probs.rds"))
    return(list(motif_probs_path = paste0(out_path, "seqXmot_probs.rds"), motif_counts_path = paste0(out_path, "seqXmot_counts.rds"))) # used by process_raw_input()
  } else {
    return(list(motif_probs = motif_probs, motif_counts = motif_counts))
  }
}
