#' Calculate PWM motif probabilities and motif counts
#'
#' @description
#' Function for calculating PWM motif probabilities using a global or
#' sequence-specific binomial approximation and counting observed PWM motif occurrences.
#'
#' Motifs should be supplied as a list of one of the following input types: Vectors with aligned binding-site sequences; or matrices with position counts (PCMs), position probabilities/frequences (PPMs), or
#' unscaled log-(odds+1) position weights (PWMs). Input motif matrices should use row order A, C, G, and T.
#'
#' @param motifs list of motif matrices or aligned binding-site vectors,
#' e.g., list(motif_1 = motif_1_input, motif_2 = motif_2_input) or list(motif_1_input, motif_2_input).
#' @param motif_type character specifying the motif representation. Should be either "motif_sites", "pcm", "ppm", or "pwm".
#' @param seqs a dataframe with the columns: 'gid', 'sequence', and optionally 'nchar' (generated by build_seq_list()).
#' @param seqlist list of processed sequences generated by build_seq_list().
#' @param threshold_type character specifying how PWM score thresholds are defined. "relative" uses a fraction of the possible PWM score range (default); and "absolute" uses the provided raw PWM score.
#' @param threshold numeric threshold used to determine whether a sequence window is classified as a motif occurrence. Can be specified as a single value or vector with one value per motif. Relative thresholds must be between zero (loose) and one (stringent).
#' Resulting cutoff is enforced on the summed PWM scores in a sequence window, and motif occurrence is defined as score sum > cutoff (threshold = cutoff in 'absolute' setting).
#' @param pwm_background character specifying the nt background probabilities used when constructing or reconstructing PWMs/PPMs.
#' "eq_nt_freq" uses equal nt frequencies and "seqs_nt_freq" uses the nt frequencies pooled across all sequences.
#' @param pseudocount numeric pseudocount added to each PCM entry.
#' @param log_base numeric base used for log-odds PWM scores (match provided PWM or use default).
#' @param motif_overlap logical specifying whether overlapping PWM motif occurrences should
#' be counted.
#' @param prob_method character specifying how the per-window motif probability P(m) is estimated.
#' "exact" enumerates all nt paths through the PWM (slow);
#' "dp" approximates the PWM score distribution using discretization and dynamic programming (faster);
#' and "global" pools motif counts across all sequences into one per-window probability used for every sequence, correcting only for seq length not nt context (rapid).
#' @param markov_order integer specifying order of the sequence-specific motif background model used by "exact" and "dp": 0 uses nucleotide frequencies (default) and 1 uses dinucleotides.
#' @param dp_resolution integer specifying number of score bins used to discretize the PWM score range in DP approx. (high resolution leads to better approx. but slower run time).
#' @param cores integer specifying number of cores used to process motifs (set to 1 for Window systems due to use of mclapply).
#'
#' @return list containing sequences X motifs matrices: motif_counts and motif_probs.
#' @export
#'
#' @examples
#' \dontrun{
#' # Character vectors of aligned motif-binding sites.
#' motif_sites <- list(RBP_1 = c("ACGT", "ACGT", "ATGT"))
#' pwm_motif_prob(motifs = motif_sites, motif_type = "motif_sites",
#' seqs = seqs, seqlist = seqlist)
#'
#' # Named lists of position count, probability, and log-odds weight matrices.
#' pcm_matrix <- matrix(c(8, 1, 1, 0, 0, 8, 1, 1,
#'                        1, 1, 8, 0, 0, 1, 1, 8),
#'                      nrow = 4,
#'                      dimnames = list(c("A", "C", "G", "T"), NULL))
#' pcm <- list(TF_1 = pcm_matrix)
#' ppm <- lapply(pcm, function(x) sweep(x + 0.25, 2, colSums(x) + 1, "/"))
#' pwm <- lapply(ppm, function(x) {
#'   log2(sweep(x, 1, c(A = 0.25, C = 0.25, G = 0.25, T = 0.25), "/") +1)})
#'
#' pwm_motif_prob(motifs = pcm, motif_type = "pcm",
#' seqs = seqs, seqlist = seqlist)
#' pwm_motif_prob(motifs = ppm, motif_type = "ppm",
#' seqs = seqs, seqlist = seqlist)
#' pwm_motif_prob(motifs = pwm, motif_type = "pwm",
#' seqs = seqs, seqlist = seqlist)
#' }
#'
#'
#'
pwm_motif_prob <- function(motifs, motif_type, seqs, seqlist, threshold_type = "relative", threshold = 0.8,
                           pwm_background = "seqs_nt_freq", pseudocount = 0.25, log_base = 2, motif_overlap = FALSE,
                           prob_method = "dp", markov_order = 1, dp_resolution = 100000, cores = parallel::detectCores()) {

  nts <- c("A", "C", "G", "T") # used to enforce row names and order

  ## Check correct input type ##
  if (!is.list(motifs)) {stop("motifs must be supplied as a list", call. = F)}

  if (!(motif_type %in% c("motif_sites", "pcm", "ppm", "pwm"))) {stop("motif_type must be either \"motif_sites\", \"pcm\", \"ppm\", or \"pwm\"", call. = F)}

  if (!(threshold_type %in% c("relative", "absolute"))) {stop("threshold_type must be either \"relative\" or \"absolute\"", call. = F)}

  if (!(markov_order %in% c(0, 1))) {stop("'markov_order' should be either 0 or 1.", call. = FALSE)}

  if (!(prob_method %in% c("exact", "dp", "global"))) {
    stop("'prob_method' should be either \"exact\", \"dp\", or \"global\".", call. = FALSE)}

  if (!(pwm_background %in% c("eq_nt_freq", "seqs_nt_freq"))) {
    stop("'pwm_background' should be either \"eq_nt_freq\" or \"seqs_nt_freq\".", call. = FALSE)}

  ## Setup PWM background ##
  # pwm_background is used to construct log-odds ratios in the PWM (obs compared to eq. or global nt contexts)
  S <- length(seqlist) # number of seqs
  seq_lens <- vapply(seqlist, function(s) s$length, integer(1L))
  seqs_freq_nt <- NULL

  if (pwm_background == "eq_nt_freq") {
    pwm_background <- c(A = 0.25, C = 0.25, G = 0.25, T = 0.25)
  } else { # use global nt freqs (pooled across all seqs)
    seqs_freq_nt <- do.call(rbind, lapply(seqlist, function(s) s$freq.mono[nts]))
    seqs_freq_nt[is.na(seqs_freq_nt)] <- 0
    pwm_background <- colSums(sweep(seqs_freq_nt, 1L, seq_lens, "*"))
    pwm_background <- pwm_background / sum(pwm_background)
  }

  # define functions to check correct input for each motif in list
  check_motif_inputs <- function(motif, motif_name) { # handle motif matrices
    if (is.data.frame(motif)) {motif <- as.matrix(motif)}

    if (!is.matrix(motif) || nrow(motif) != 4L || ncol(motif) < 1) {
      stop(paste0("Motif '", motif_name, "' should be a 4 x k matrix with k >= 1, where k = motif length."), call. = FALSE)}

    row_nt <- rownames(motif)
    if (is.null(row_nt) || !setequal(row_nt, nts)) {
      stop(paste0("Motif '", motif_name, "' should only contain rows named with uppercase A, C, G, and T."), call. = FALSE)}

    motif <- motif[nts, , drop = FALSE] # reorder rows to ensure correct order
    colnames(motif) <- NULL
    return(motif)
  }

  sites_to_pcm <- function(sites, motif_name) { # handle motif binding sites (character vector)
    # check input
    if (!is.character(sites) || length(sites) < 1 || anyNA(sites)) {
      stop(paste0("Binding sites for motif '", motif_name, "' should be a non-empty character vector."), call. = FALSE)}

    site_widths <- nchar(sites) # k
    if (any(site_widths < 1) ||length(unique(site_widths)) != 1) {
      stop(paste0("Binding sites for motif '", motif_name, "' should all have the same positive width."), call. = FALSE)}

    if (any(grepl("[^ACGT]", sites))) {stop(
      paste0("Binding sites for motif '", motif_name, "' should only contain uppercase A, C, G, and T."), call. = FALSE)}

    # create pcm matrix from binding sites
    pcm <- vapply(seq_len(site_widths[1]), function(pos) {tabulate(match(substr(sites, pos, pos), nts), nbins = 4)}, integer(4))
    dimnames(pcm) <- list(nts, NULL)
    return(pcm)
  }

  # check motif names in list
  M <- length(motifs) # number of motifs
  motif_names <- names(motifs)
  if (is.null(motif_names)) {motif_names <- paste0("motif_", 1:M)} # assign names

  # convert threshold input to one value per motif
  if (length(threshold) == 1) {threshold <- rep(as.numeric(threshold), M)
  } else if (length(threshold) == M) {threshold <- as.numeric(threshold)
  } else {stop("'threshold' should have length one or a value per motif.", call. = FALSE)}

  if (threshold_type == "relative" && any(threshold < 0 | threshold > 1)) {
    stop("Relative thresholds should be between zero and one.", call. = FALSE)}

  ## Convert all motif representations into PWMs ##
  pwm_list <- lapply(seq_along(motifs), function(motif_idx) {
    motif_name <- motif_names[[motif_idx]]
    motif <- motifs[[motif_idx]]

    if (motif_type == "motif_sites") {
      pcm <- sites_to_pcm(motif, motif_name)
      ppm <- sweep(pcm + pseudocount, 2, colSums(pcm) + 4 * pseudocount, "/") # prob = freqs + pseudocount
      pwm <- log(sweep(ppm, 1, pwm_background, "/") +1, base = log_base) # add +1 to avoid log(0)

    } else { # matrix inputs
      motif <- check_motif_inputs(motif, motif_name)
      if (motif_type %in% c("pcm", "ppm") && (any(!is.finite(motif)) || any(motif < 0))) {
        stop(paste0("PCM/PPM '", motif_name, "' should contain finite non-negative values."), call. = FALSE)}

      if (motif_type == "pcm") {
        ppm <- sweep(motif + pseudocount, 2, colSums(motif) + 4 * pseudocount, "/")
        pwm <- log(sweep(ppm, 1L, pwm_background, "/") +1, base = log_base)

      } else if (motif_type == "ppm") {
        # check columns sum to one, allow for rounding imprecisions
        ppm_col_sums <- colSums(motif)
        if (any(abs(ppm_col_sums - 1) > 1e-6)) {stop(paste0("Columns of PPM '", motif_name, "' should sum to one."), call. = FALSE)}
        ppm <- sweep(motif, 2, ppm_col_sums, "/") # force col sums to one
        # construct pwm
        pwm <- log(sweep(ppm, 1, pwm_background, "/") +1, base = log_base)
      } else {
        # PWM input is assumed to contain unscaled log-odds scores
        if (any(!is.finite(motif))) {stop(paste0("PWM '", motif_name, "' should contain finite log-odds scores."), call. = FALSE)}

        if (any(motif < 0) || all(motif == 0)){ # log-odds
          pwm <- motif
          # reconstruct the PPM corresponding to the supplied log-odds PWM (assuming same nt background as pwm_background)
          ppm <- sweep(log_base^pwm, 1, pwm_background, "*")
          pwm <- log(sweep(ppm, 1, pwm_background, "/") +1, base = log_base)
        } else { # log-(odds+1)
          pwm <- motif
          ppm <- sweep(log_base^pwm -1, 1, pwm_background, "*")  # -1 assumes +1 was added to the PWM during log transformation!
        }

        # check columns sum to one
        ppm_col_sums <- colSums(ppm)
        if (any(!is.finite(ppm_col_sums)) || any(ppm_col_sums <= 0)) {
          stop(paste0("PPM reconstruction failed for PWM '", motif_name, "'."), call. = FALSE)}

        if (any(abs(ppm_col_sums - 1) > 1e-4)) {
          warning(paste0("PWM '", motif_name, "' does not reconstruct PPM columns summing to one. ",
                         "Ensure that the provided PWM contains unscaled log-odds scores and that pwm_background ",
                         "matches the background used to construct the PWM."), call. = FALSE)}
      }
    }
    if (any(!is.finite(pwm))) {stop(paste0("PWM construction produced non-finite scores for motif '", motif_name, "'."), call. = FALSE)}
    rownames(pwm) <- nts
    pwm # return motif pwm
  })
  names(pwm_list) <- motif_names

  ## Pre-compute seq representations and indexing ##
  seq_ids <- seqs$gid
  nt_idx <- c(A = 1L, C = 2L, G = 3L, T = 4L) # integer indexing (possible due to consistent ordering)
  seq_idx <- lapply(seqlist, function(s) unname(nt_idx[strsplit(s$sequence, "", fixed = TRUE)[[1L]]])) # convert each seq to integer indexes once

  if (prob_method != "global") {
    if (is.null(seqs_freq_nt)) { # avoid constructing seqs_freq_nt twice when pwm_background == "seqs_nt_freq"
      seqs_freq_nt <- do.call(rbind, lapply(seqlist, function(s) s$freq.mono[nts])) # store nt freqs as an S x 4 matrix
      seqs_freq_nt[is.na(seqs_freq_nt)] <- 0 # when a nt is unpresent
    }
    dimnames(seqs_freq_nt) <- list(seq_ids, nts)

    if (markov_order == 1L) {
      # store conditional probabilities (di-nt) once as 4 (m_i) x 4 (m_i-1) x S array.
      # NOTE: con.prob.di columns sum to 1, so con.prob.di[i, j] = P(m_i = i | m_i-1 = j).
      cond_prob <- array(unlist(lapply(seqlist, function(s) as.numeric(s$con.prob.di[nts, nts])), use.names = FALSE), dim = c(4L, 4L, S))
      cond_prob[!is.finite(cond_prob)] <- 0
    }
  }

  ## Calculate the probability that a seq window passes PWM threshold (entailing motif occurrence) ##

  # Given the sequence-specific nt or di-nt freq, we calculate the prob that an arbitrary seq window (with length k matching the PWM motif length) passes the cutoff for motif occ. This corresponds to P(m); the per-window motif-occurrence probability.
  # Note, the cutoff is defined based on the threshold (cutoff = threshold only for threshold_type = "absolute").

  # Exact P(m): enumerate all 4^k nt paths scored by the PWM (path = possible motif realization, e.g., 'AGCCT' for k = 5; branch = set of paths 'AG---').
  # Very slow, even with branches pruned by remaining min/max score bounds.
  pwm_prob_in_seq_window_exact <- function(pwm, cutoff, seqs_freq_nt, cond_prob = NULL) { # cond_prob is used only for markov_order = 1

    n_seqs_eval <- nrow(seqs_freq_nt) # nr of seqs evaluated
    motif_width <- ncol(pwm) # size of considered seq window
    min_score_by_pos <- apply(pwm, 2L, min) # min PWM (log-odds) score for each pos in motif
    max_score_by_pos <- apply(pwm, 2L, max) # max PWM (log-odds) score for each pos in motif

    # remaining score bounds allow early stopping if the cutoff is guaranteed to be reached or missed.
    min_score_remaining <- rev(cumsum(rev(min_score_by_pos))) # min total score still possible from each pos to motif end.
    max_score_remaining <- rev(cumsum(rev(max_score_by_pos))) # max total possible score reachable from each pos to end.

    window_prob <- numeric(n_seqs_eval) # P(m): per-seq probability that a PWM-width window passes the score cutoff (motif occ.)

    # deterministic branch-and-bound algorithm: Grow each nt branch one position at a time (max length = k).
    # At 'pos', 'branch_score' is the cumulative PWM score across positions 1:(pos - 1),
    # while 'branch_prob' (vector) contains the prob of the growing branch for every evaluated seq.
    # Remaining min/max score bounds stop enumeration when every or no possible path on the branch can pass the cutoff.
    enumerate_window_branches <- function(pos, branch_score, branch_prob, previous_nt = 0) {

      # stop branch eval if growing branch has zero prob in every seq (no path on branch will pass cutoff)
      if (all(branch_prob == 0)) {return(invisible(NULL))}

      # stop branch eval if no possible completion can pass the cutoff
      if (branch_score + max_score_remaining[pos] <= cutoff) {return(invisible(NULL))}

      # stop branch eval if all possible completions can pass the cutoff
      if (branch_score + min_score_remaining[pos] > cutoff) {
        window_prob <<- window_prob + branch_prob # update P(m)
        return(invisible(NULL))}

      # score of the growing branch extended by current_nt at pos
      for (current_nt in 1:4) { # A, C, G, T
        extended_score <- branch_score + pwm[current_nt, pos]

        if (pos == 1) {# first position has no previous nt to condition on; use the marginal nt freq.
          extended_prob <- branch_prob * seqs_freq_nt[, current_nt]

        } else if (is.null(cond_prob)) {# order 0: draws are independent, so always use the marginal nt freq.
          extended_prob <- branch_prob * seqs_freq_nt[, current_nt]

        } else { # order 1: condition on the nt drawn at the previous position.
          extended_prob <- branch_prob * cond_prob[current_nt, previous_nt,]
        }
        if (pos == motif_width) {
          if (extended_score > cutoff) { # completed path is a motif occurrence
            window_prob <<- window_prob + extended_prob}

        } else { # continue evaluating the extended branch at the next position (recursion)
          enumerate_window_branches(pos = pos + 1, branch_score = extended_score,
                                    branch_prob = extended_prob, previous_nt = current_nt)
        }
      }
      invisible(NULL)
    }
    # start from an empty branch root (score = 0, prob = 1) at pos = 1
    enumerate_window_branches(pos = 1, branch_score = 0, branch_prob = rep(1, n_seqs_eval))

    return(pmin(pmax(window_prob, 0), 1)) # Return P(m)
  }

  ## Count PWM motif occurrences ##
  # scan seq for (sliding) windows with summed PWM score > cutoff (obtained from threshold).
  scan_pwm_occurrences <- function(encoded_seq, # A,C,G,T -> 1,2,3,4
                                   pwm, cutoff, motif_overlap) {

    motif_width <- ncol(pwm)
    seq_len <- length(encoded_seq)
    n_windows <- seq_len - motif_width + 1 # = trials, nr window pos with possible mot occ.

    if (n_windows <= 0) {return(c(motif_count = 0, motif_windows = 0))} # seq shorter than the motif

    pwm_scores <- numeric(n_windows) # 0-vector to track summed PWM score for each window start pos (each seq pos will get diff score depending on where it is in the PWM motif)

    for (mot_pos in 1:motif_width) {
      seq_positions <- mot_pos:(mot_pos + n_windows - 1) # seq idx for mot_pos in each window
      pwm_idx <- encoded_seq[seq_positions] + 4 * (mot_pos - 1) # idx for PWM (nt=4 X k) entry retrieval
      pwm_scores <- pwm_scores + pwm[pwm_idx] # update summed PWM scores with next pos in motif
    }
    occ_positions <- which(pwm_scores > cutoff) # window starts with sum scores > cutoff = potential mot occ.
    n_mot_windows <- length(occ_positions)

    if (n_mot_windows == 0) {return(c(motif_count = 0, motif_windows = 0))} # no mot occ.

    if (motif_overlap) { # return all occ. if motif_overlap = TRUE
      return(c(motif_count = n_mot_windows, # used for returned motif_counts matrix
               motif_windows = n_mot_windows)) # used to calculate P(m) in global setting
    }
    # no motif overlap (remove overlapping motif_windows)
    n_occ <- 0
    next_allowed_pos <- 1
    # retain the leftmost occurrence and skip all overlapping start pos
    for (occ_pos in occ_positions) {
      if (occ_pos >= next_allowed_pos) {
        n_occ <- n_occ + 1
        next_allowed_pos <- occ_pos + motif_width
      }
    }
    return(c(motif_count = n_occ, motif_windows = n_mot_windows))
  }

  ## Calculate sequence-specific motif counts and SSPs (under binomial model) ##
  motif_count_SSP <- function(motif_idx) {
    pwm <- pwm_list[[motif_idx]]
    motif_width <- ncol(pwm)

    min_pwm_score <- sum(apply(pwm, 2, min)) # min possible score for seq window under PWM (window width = PWM/motif width)
    max_pwm_score <- sum(apply(pwm, 2, max)) # max possible score for seq window under PWM
    trials <- pmax(seq_lens - motif_width + 1, 0) # nr of positions where the motif can potentially occur in the seq

    # define cutoff from threshold
    if(threshold_type == "relative"){cutoff <- min_pwm_score + threshold[[motif_idx]] * (max_pwm_score - min_pwm_score)} # map relative threshold onto PWM score range (0 = min; 1 = max)
    if(threshold_type == "absolute"){cutoff <- threshold[[motif_idx]]} #  +motif_width*log(2, base = log_base) - adjust for adding +1 to the PWM avoiding log(0). Shift cutoff accordingly (let the user decide)

    ## Motif counts ##
    # stop scan early if every or no seq window will pass cutoff
    if (cutoff < min_pwm_score) { # motif occ. at every possible window
      if (motif_overlap) {
        motif_counts <- trials
      } else {
        motif_counts <- seq_lens %/% motif_width # every possible nonoverlapping site has motif occ.
      }
      n_motif_windows <- trials
    } else if (cutoff >= max_pwm_score) { # no motif occ. at every possible window
      motif_counts <- integer(S) # 0-vector of length S (nr seqs)
      n_motif_windows <- integer(S)

    } else { # scan for motif occ. in each seq
      motif_scan <- vapply(seq_idx, scan_pwm_occurrences,
                           c(motif_count = 0, motif_windows = 0), pwm = pwm, cutoff = cutoff, motif_overlap = motif_overlap)
      motif_counts <- motif_scan["motif_count", ]
      n_motif_windows <- motif_scan["motif_windows", ]
    }

    ## Motif probs ##
    motif_probs <- numeric(S) # 0-vector starting point
    seqs_eval <- trials > 0 # seqs long enough to fit at least one window
    if (any(seqs_eval)) {
      if (cutoff < min_pwm_score) { # every window will pass
        window_prob <- 1
      } else if (cutoff >= max_pwm_score) { # no window will pass
        window_prob <- 0 # no window can pass
      } else if (prob_method == "global") {
        # pooled occ. rate across all evaluated seqs; corrects for seq length only, not nt composition.
        window_prob <- sum(n_motif_windows) / sum(trials)
      } else { # get seq specific window prob of motif occ. P(m)
        seqs_freq_nt_eval <- seqs_freq_nt[seqs_eval, , drop = FALSE] # P(m_i)
        if(markov_order == 0){cond_prob_eval <- NULL}
        if(markov_order == 1){cond_prob_eval <- cond_prob[, , seqs_eval, drop = FALSE]} # P(m_i | m_{i-1})

        if(prob_method == "exact"){window_prob <- pwm_prob_in_seq_window_exact(pwm, cutoff, seqs_freq_nt_eval, cond_prob_eval)} # P(m)
        if(prob_method == "dp"){window_prob <- pwm_prob_in_seq_window_DP(pwm, cutoff, seqs_freq_nt_eval, cond_prob_eval, dp_resolution)} # bayesReact:::
      }
      window_prob <- pmin(pmax(window_prob, 0), 1) # avoid floating point issues

      # binomial SSP: P(n_m >= 1) = 1 - (1 - P(m))^trials.
      motif_probs[seqs_eval] <- -expm1(trials[seqs_eval] * log1p(-window_prob))
    }
    return(list(motif_probs = motif_probs, motif_counts = motif_counts))
  }

  ## Get motif_counts and probs ##
  motif_results <- parallel::mclapply(1:M, motif_count_SSP, mc.cores = cores)

  motif_counts <- do.call(cbind, lapply(motif_results, `[[`, "motif_counts"))
  motif_probs <- do.call(cbind, lapply(motif_results, `[[`, "motif_probs"))
  dimnames(motif_counts) <- list(seq_ids, motif_names)
  dimnames(motif_probs) <- list(seq_ids, motif_names)

  if (any(!is.finite(motif_probs))) {stop("Invalid PWM motif probabilities were produced.", call. = FALSE)} # avoid NA
  return(list(motif_probs = motif_probs, motif_counts = motif_counts))
}
